### ISSUE TITLE
Static server should guess mimetypes

### ISSUE THREAD

**Issue by ecumene** [fermyon/spin-kitchensink#12]
The static server doesn't guess mimetypes like other servers. I think this is pretty easy to fix, I've got a working example here:

https://gist.github.com/ecumene/9be9a4cef1a4e7b4466c61999787cedb

**Comment by radu-matei** [comment]
Hi, @ecumene, thanks for the issue!

The file server we are using in most places (to serve the Spin docs and Fermyon.com) is https://github.com/fermyon/spin-fileserver, which does try to guess mime types.

Does this help?

**Comment by ecumene** [comment]
🤦 I thought this was the static file server example 

My bad

**Comment by radu-matei** [comment]
Yeah, sorry about the confusion.. wanted to provide an easy example, but not re-implement the entire file server.

What do you think should be a better experience here?

**Comment by ecumene** [comment]
No it's all good, I learned a lot doing it myself to be honest (mimetype strings being called `essence` was news to me)

I don't know how to make this any better, I should have searched more I think. This is the nature of the beast since things are so early.
